-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_sha3_pedantic]: function definitions
import Aeneas
import CoreModels
import HacspecSha3Pedantic.Extraction.Types
import HacspecSha3Pedantic.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_sha3_pedantic

/-- [hacspec_sha3_pedantic::bits::trunc]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 24:4-26:5
    Visibility: public -/
@[rust_loop_body]
def bits.trunc_loop.body
  (x : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::bits::trunc]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 24:4-26:5
    Visibility: public -/
@[rust_loop]
def bits.trunc_loop
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.trunc_loop.body x iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::bits::trunc]:
    Source: 'sha3-pedantic/src/bits.rs', lines 21:0-28:1
    Visibility: public -/
def bits.trunc
  (x : Slice Bool) (s : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len x
  massert (s <= i)
  let out ← alloc.vec.Vec.new Bool
  bits.trunc_loop { start := 0#usize, «end» := s } x out

/-- [hacspec_sha3_pedantic::bits::zeros]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 33:4-35:5
    Visibility: public -/
@[rust_loop_body]
def bits.zeros_loop.body
  (iter : core.ops.range.Range Std.Usize) (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some _ =>
    let out1 ← alloc.vec.Vec.push out false
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::bits::zeros]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 33:4-35:5
    Visibility: public -/
@[rust_loop]
def bits.zeros_loop
  (iter : core.ops.range.Range Std.Usize) (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.zeros_loop.body iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::bits::zeros]:
    Source: 'sha3-pedantic/src/bits.rs', lines 31:0-37:1
    Visibility: public -/
def bits.zeros (n : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let out ← alloc.vec.Vec.new Bool
  bits.zeros_loop { start := 0#usize, «end» := n } out

/-- [hacspec_sha3_pedantic::bits::concat]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 42:4-44:5
    Visibility: public -/
@[rust_loop_body]
def bits.concat_loop0.body
  (x : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::bits::concat]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 42:4-44:5
    Visibility: public -/
@[rust_loop]
def bits.concat_loop0
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.concat_loop0.body x iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::bits::concat]: loop body 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 45:4-47:5
    Visibility: public -/
@[rust_loop_body]
def bits.concat_loop1.body
  (y : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize y i
    let out1 ← alloc.vec.Vec.push out b
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::bits::concat]: loop 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 45:4-47:5
    Visibility: public -/
@[rust_loop]
def bits.concat_loop1
  (iter : core.ops.range.Range Std.Usize) (y : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.concat_loop1.body y iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::bits::concat]:
    Source: 'sha3-pedantic/src/bits.rs', lines 40:0-49:1
    Visibility: public -/
def bits.concat
  (x : Slice Bool) (y : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let out ← alloc.vec.Vec.new Bool
  let i ← core.slice.Slice.len x
  let out1 ← bits.concat_loop0 { start := 0#usize, «end» := i } x out
  let i1 ← core.slice.Slice.len y
  bits.concat_loop1 { start := 0#usize, «end» := i1 } y out1

/-- [hacspec_sha3_pedantic::bits::xor]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 59:4-61:5
    Visibility: public -/
@[rust_loop_body]
def bits.xor_loop.body
  (x : Slice Bool) (y : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some i =>
    let b ← Slice.index_usize x i
    let b1 ← Slice.index_usize y i
    let out1 ← alloc.vec.Vec.push out (b ^^ b1)
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::bits::xor]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 59:4-61:5
    Visibility: public -/
@[rust_loop]
def bits.xor_loop
  (iter : core.ops.range.Range Std.Usize) (x : Slice Bool) (y : Slice Bool)
  (out : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, out1) => bits.xor_loop.body x y iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::bits::xor]:
    Source: 'sha3-pedantic/src/bits.rs', lines 53:0-63:1
    Visibility: public -/
def bits.xor
  (x : Slice Bool) (y : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len x
  let i1 ← core.slice.Slice.len y
  massert (i = i1)
  let out ← alloc.vec.Vec.new Bool
  bits.xor_loop { start := 0#usize, «end» := i } x y out

/-- [hacspec_sha3_pedantic::bits::h2b]: loop body 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 78:8-80:9
    Visibility: public -/
@[rust_loop_body]
def bits.h2b_loop0_loop0.body
  (byte : Std.U8) (iter : core.ops.range.Range Std.I32)
  (t : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.I32) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.I32.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done t)
  | core.option.Option.Some j =>
    let i ← byte >>> j
    let i1 ← lift (i &&& 1#u8)
    let t1 ← alloc.vec.Vec.push t (i1 = 1#u8)
    ok (cont (iter1, t1))

/-- [hacspec_sha3_pedantic::bits::h2b]: loop 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 78:8-80:9
    Visibility: public -/
@[rust_loop]
def bits.h2b_loop0_loop0
  (iter : core.ops.range.Range Std.I32) (t : alloc.vec.Vec Bool)
  (byte : Std.U8) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, t1) => bits.h2b_loop0_loop0.body byte iter1 t1)
    (iter, t)

/-- [hacspec_sha3_pedantic::bits::h2b]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 76:4-81:5
    Visibility: public -/
@[rust_loop_body]
def bits.h2b_loop0.body
  (h : Slice Std.U8) (iter : core.ops.range.Range Std.Usize)
  (t : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done t)
  | core.option.Option.Some i =>
    let byte ← Slice.index_usize h i
    let t1 ← bits.h2b_loop0_loop0 { start := 0#i32, «end» := 8#i32 } t byte
    ok (cont (iter1, t1))

/-- [hacspec_sha3_pedantic::bits::h2b]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 76:4-81:5
    Visibility: public -/
@[rust_loop]
def bits.h2b_loop0
  (iter : core.ops.range.Range Std.Usize) (h : Slice Std.U8)
  (t : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, t1) => bits.h2b_loop0.body h iter1 t1)
    (iter, t)

/-- [hacspec_sha3_pedantic::bits::h2b]:
    Source: 'sha3-pedantic/src/bits.rs', lines 73:0-83:1
    Visibility: public -/
def bits.h2b
  (h : Slice Std.U8) (n : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len h
  let i1 ← 8#usize * i
  massert (n <= i1)
  let t ← alloc.vec.Vec.new Bool
  let t1 ← bits.h2b_loop0 { start := 0#usize, «end» := i } h t
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref t1
  bits.trunc s n

/-- [hacspec_sha3_pedantic::bits::h2b_full]:
    Source: 'sha3-pedantic/src/bits.rs', lines 86:0-88:1
    Visibility: public -/
def bits.h2b_full (h : Slice Std.U8) : RustM (alloc.vec.Vec Bool) := do
  let i ← core.slice.Slice.len h
  let i1 ← 8#usize * i
  bits.h2b h i1

/-- [hacspec_sha3_pedantic::bits::b2h]: loop body 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 101:8-105:9
    Visibility: public -/
@[rust_loop_body]
def bits.b2h_loop0_loop0.body
  (t : alloc.vec.Vec Bool) (i : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (byte : Std.U8) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U8) Std.U8)
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done byte)
  | core.option.Option.Some j =>
    let i1 ← 8#usize * i
    let i2 ← i1 + j
    let b ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT Bool) t i2
    if b
    then
      let i3 ← 1#u8 <<< j
      let byte1 ← lift (byte ||| i3)
      ok (cont (iter1, byte1))
    else ok (cont (iter1, byte))

/-- [hacspec_sha3_pedantic::bits::b2h]: loop 1:
    Source: 'sha3-pedantic/src/bits.rs', lines 101:8-105:9
    Visibility: public -/
@[rust_loop]
def bits.b2h_loop0_loop0
  (iter : core.ops.range.Range Std.Usize) (t : alloc.vec.Vec Bool)
  (i : Std.Usize) (byte : Std.U8) :
  RustM Std.U8
  := do
  loop
    (fun (iter1, byte1) => bits.b2h_loop0_loop0.body t i iter1 byte1)
    (iter, byte)

/-- [hacspec_sha3_pedantic::bits::b2h]: loop body 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 99:4-107:5
    Visibility: public -/
@[rust_loop_body]
def bits.b2h_loop0.body
  (t : alloc.vec.Vec Bool) (iter : core.ops.range.Range Std.Usize)
  (h : alloc.vec.Vec Std.U8) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec
    Std.U8)) (alloc.vec.Vec Std.U8))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done h)
  | core.option.Option.Some i =>
    let byte ←
      bits.b2h_loop0_loop0 { start := 0#usize, «end» := 8#usize } t i 0#u8
    let h1 ← alloc.vec.Vec.push h byte
    ok (cont (iter1, h1))

/-- [hacspec_sha3_pedantic::bits::b2h]: loop 0:
    Source: 'sha3-pedantic/src/bits.rs', lines 99:4-107:5
    Visibility: public -/
@[rust_loop]
def bits.b2h_loop0
  (iter : core.ops.range.Range Std.Usize) (t : alloc.vec.Vec Bool)
  (h : alloc.vec.Vec Std.U8) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (iter1, h1) => bits.b2h_loop0.body t iter1 h1)
    (iter, h)

/-- [hacspec_sha3_pedantic::bits::b2h]:
    Source: 'sha3-pedantic/src/bits.rs', lines 94:0-109:1
    Visibility: public -/
def bits.b2h (s : Slice Bool) : RustM (alloc.vec.Vec Std.U8) := do
  let n ← core.slice.Slice.len s
  let i ← n % 8#usize
  let i1 ← 8#usize - i
  let i2 ← i1 % 8#usize
  let v ← bits.zeros i2
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let t ← bits.concat s s1
  let i3 ← alloc.vec.Vec.len t
  let m ← i3 / 8#usize
  let h ← alloc.vec.Vec.new Std.U8
  bits.b2h_loop0 { start := 0#usize, «end» := m } t h

/-- [hacspec_sha3_pedantic::sponge::pad10_star_1]: loop body 0:
    Source: 'sha3-pedantic/src/sponge.rs', lines 16:4-18:5
    Visibility: public -/
@[rust_loop_body]
def sponge.pad10_star_1_loop.body
  (iter : core.ops.range.Range Std.I64) (p : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.I64) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.I64.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done p)
  | core.option.Option.Some _ =>
    let p1 ← alloc.vec.Vec.push p false
    ok (cont (iter1, p1))

/-- [hacspec_sha3_pedantic::sponge::pad10_star_1]: loop 0:
    Source: 'sha3-pedantic/src/sponge.rs', lines 16:4-18:5
    Visibility: public -/
@[rust_loop]
def sponge.pad10_star_1_loop
  (iter : core.ops.range.Range Std.I64) (p : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, p1) => sponge.pad10_star_1_loop.body iter1 p1)
    (iter, p)

/-- [hacspec_sha3_pedantic::sponge::pad10_star_1]:
    Source: 'sha3-pedantic/src/sponge.rs', lines 11:0-21:1
    Visibility: public -/
def sponge.pad10_star_1
  (x : Std.Usize) (m : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let x_i ← lift (UScalar.hcast .I64 x)
  let i ← lift (UScalar.hcast .I64 m)
  let i1 ← -. i
  let i2 ← i1 - 2#i64
  let i3 ← i2 % x_i
  let i4 ← i3 + x_i
  let j ← i4 % x_i
  let p ← alloc.vec.Vec.new Bool
  let p1 ← alloc.vec.Vec.push p true
  let p2 ← sponge.pad10_star_1_loop { start := 0#i64, «end» := j } p1
  alloc.vec.Vec.push p2 true

/-- [hacspec_sha3_pedantic::sponge::{impl hacspec_sha3_pedantic::sponge::Components for hacspec_sha3_pedantic::sponge::Keccak1600}::pad]:
    Source: 'sha3-pedantic/src/sponge.rs', lines 85:4-87:5
    Visibility: public -/
def sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents.pad
  (self : sponge.Keccak1600) (x : Std.Usize) (m : Std.Usize) :
  RustM (alloc.vec.Vec Bool)
  := do
  sponge.pad10_star_1 x m

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::B]
    Source: 'sha3-pedantic/src/state_array.rs', lines 27:4-27:32
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.B (W : Std.Usize) : RustM Std.Usize := 25#usize * W

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop body 2:
    Source: 'sha3-pedantic/src/state_array.rs', lines 77:16-79:17
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0_loop0_loop0.body
  {W : Std.Usize} (self : state_array.StateArray W) (y : Std.Usize)
  (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    ((state_array.StateArray W) × (alloc.vec.Vec Bool)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (self, s))
  | core.option.Option.Some z =>
    let a ← Array.index_usize self.a x
    let _ ← Array.index_usize a y
    let a1 ← Array.index_usize a y
    let b ← Array.index_usize a1 z
    let s1 ← alloc.vec.Vec.push s b
    ok (cont (iter1, s1))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop 2:
    Source: 'sha3-pedantic/src/state_array.rs', lines 77:16-79:17
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) (y : Std.Usize)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (iter1, s1) => state_array.StateArray.to_bits_loop0_loop0_loop0.body
      self y x iter1 s1)
    (iter, s)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop body 1:
    Source: 'sha3-pedantic/src/state_array.rs', lines 76:12-80:13
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0_loop0.body
  {W : Std.Usize} (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (alloc.vec.Vec Bool))
    ((state_array.StateArray W) × (alloc.vec.Vec Bool)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (self, s))
  | core.option.Option.Some x =>
    let (self1, s1) ←
      state_array.StateArray.to_bits_loop0_loop0_loop0
        { start := 0#usize, «end» := W } self s y x
    ok (cont (iter1, self1, s1))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop 1:
    Source: 'sha3-pedantic/src/state_array.rs', lines 76:12-80:13
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (alloc.vec.Vec Bool))
  := do
  loop
    (fun (iter1, self1, s1) => state_array.StateArray.to_bits_loop0_loop0.body
      y iter1 self1 s1)
    (iter, self, s)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop body 0:
    Source: 'sha3-pedantic/src/state_array.rs', lines 75:8-81:9
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.to_bits_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (alloc.vec.Vec Bool)) (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done s)
  | core.option.Option.Some y =>
    let (self1, s1) ←
      state_array.StateArray.to_bits_loop0_loop0
        { start := 0#usize, «end» := 5#usize } self s y
    ok (cont (iter1, self1, s1))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]: loop 0:
    Source: 'sha3-pedantic/src/state_array.rs', lines 75:8-81:9
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.to_bits_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (self : state_array.StateArray W) (s : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, self1, s1) => state_array.StateArray.to_bits_loop0.body iter1
      self1 s1)
    (iter, self, s)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::to_bits]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 73:4-83:5
    Visibility: public -/
def state_array.StateArray.to_bits
  {W : Std.Usize} (self : state_array.StateArray W) :
  RustM (alloc.vec.Vec Bool)
  := do
  let i ← state_array.StateArray.B W
  let s ← alloc.vec.Vec.with_capacity Bool i
  state_array.StateArray.to_bits_loop0 { start := 0#usize, «end» := 5#usize }
    self s

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::zero]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 47:4-51:5
    Visibility: public -/
def state_array.StateArray.zero
  (W : Std.Usize) : RustM (state_array.StateArray W) := do
  let a := Array.repeat W false
  let a1 := Array.repeat 5#usize a
  let a2 := Array.repeat 5#usize a1
  ok { a := a2 }

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop body 2:
    Source: 'sha3-pedantic/src/state_array.rs', lines 60:16-62:17
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0_loop0_loop0.body
  {W : Std.Usize} (s : Slice Bool) (x : Std.Usize) (y : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some z =>
    let i ← 5#usize * y
    let i1 ← i + x
    let i2 ← W * i1
    let i3 ← i2 + z
    let b ← Slice.index_usize s i3
    let a ← Array.index_usize out.a x
    let _ ← Array.index_usize a y
    let (a1, index_mut_back) ← Array.index_mut_usize out.a x
    let (a2, index_mut_back1) ← Array.index_mut_usize a1 y
    let a3 ← Array.update a2 z b
    let a4 := index_mut_back1 a3
    let a5 := index_mut_back a4
    ok (cont (iter1, { a := a5 }))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop 2:
    Source: 'sha3-pedantic/src/state_array.rs', lines 60:16-62:17
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) (x : Std.Usize) (y : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) =>
      state_array.StateArray.from_bits_loop0_loop0_loop0.body s x y iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop body 1:
    Source: 'sha3-pedantic/src/state_array.rs', lines 59:12-63:13
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0_loop0.body
  {W : Std.Usize} (s : Slice Bool) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some y =>
    let out1 ←
      state_array.StateArray.from_bits_loop0_loop0_loop0
        { start := 0#usize, «end» := W } s out x y
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop 1:
    Source: 'sha3-pedantic/src/state_array.rs', lines 59:12-63:13
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) (x : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) => state_array.StateArray.from_bits_loop0_loop0.body s x
      iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop body 0:
    Source: 'sha3-pedantic/src/state_array.rs', lines 58:8-64:9
    Visibility: public -/
@[rust_loop_body]
def state_array.StateArray.from_bits_loop0.body
  {W : Std.Usize} (s : Slice Bool) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let out1 ←
      state_array.StateArray.from_bits_loop0_loop0
        { start := 0#usize, «end» := 5#usize } s out x
    ok (cont (iter1, out1))

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]: loop 0:
    Source: 'sha3-pedantic/src/state_array.rs', lines 58:8-64:9
    Visibility: public -/
@[rust_loop]
def state_array.StateArray.from_bits_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (s : Slice Bool)
  (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, out1) => state_array.StateArray.from_bits_loop0.body s iter1
      out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 55:4-66:5
    Visibility: public -/
def state_array.StateArray.from_bits
  (W : Std.Usize) (s : Slice Bool) : RustM (state_array.StateArray W) := do
  let i ← core.slice.Slice.len s
  let i1 ← 25#usize * W
  massert (i = i1)
  let out ← state_array.StateArray.zero W
  state_array.StateArray.from_bits_loop0
    { start := 0#usize, «end» := 5#usize } s out

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::L]
    Source: 'sha3-pedantic/src/state_array.rs', lines 35:4-44:6
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.L (W : Std.Usize) : RustM Std.Usize :=
  match W.val with
  | 1 => ok 0#usize
  | 2 => ok 1#usize
  | 4 => ok 2#usize
  | 8 => ok 3#usize
  | 16 => ok 4#usize
  | 32 => ok 5#usize
  | 64 => ok 6#usize
  | _ => fail panic

/-- [hacspec_sha3_pedantic::step_mappings::imod]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 13:0-15:1 -/
def step_mappings.imod (a : Std.I64) (b : Std.I64) : RustM Std.Usize := do
  let i ← a % b
  let i1 ← i + b
  let i2 ← i1 % b
  ok (IScalar.hcast .Usize i2)

/-- [hacspec_sha3_pedantic::step_mappings::rc]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 120:4-135:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rc_loop.body
  (iter : core.ops.range.RangeInclusive Std.Usize) (r : Array Bool 9#usize) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.Usize) × (Array Bool
    9#usize)) (Array Bool 9#usize))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done r)
  | core.option.Option.Some _ =>
    let shifted := Array.repeat 9#usize false
    let (s, index_mut_back) ←
      core.Array.Insts.CoreOpsIndexIndexMut.index_mut
        (core.Slice.Insts.CoreOpsIndexIndexMut
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Bool)) shifted { start := 1#usize, «end» := 9#usize }
    let s1 ←
      core.Array.Insts.CoreOpsIndexIndex.index
        (core.Slice.Insts.CoreOpsIndexIndex
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Bool)) r { start := 0#usize, «end» := 8#usize }
    let s2 ←
      core.slice.Slice.copy_from_slice core.Bool.Insts.CoreMarkerCopy s s1
    let shifted1 := index_mut_back s2
    let b ← Array.index_usize shifted1 8#usize
    let b1 ← Array.index_usize shifted1 0#usize
    let shifted2 ← Array.update shifted1 0#usize (b1 ^^ b)
    let b2 ← Array.index_usize shifted2 8#usize
    let b3 ← Array.index_usize shifted2 4#usize
    let shifted3 ← Array.update shifted2 4#usize (b3 ^^ b2)
    let b4 ← Array.index_usize shifted3 8#usize
    let b5 ← Array.index_usize shifted3 5#usize
    let shifted4 ← Array.update shifted3 5#usize (b5 ^^ b4)
    let b6 ← Array.index_usize shifted4 8#usize
    let b7 ← Array.index_usize shifted4 6#usize
    let shifted5 ← Array.update shifted4 6#usize (b7 ^^ b6)
    let a ← Array.update shifted5 8#usize false
    ok (cont (iter1, a))

/-- [hacspec_sha3_pedantic::step_mappings::rc]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 120:4-135:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rc_loop
  (iter : core.ops.range.RangeInclusive Std.Usize) (r : Array Bool 9#usize) :
  RustM (Array Bool 9#usize)
  := do
  loop
    (fun (iter1, r1) => step_mappings.rc_loop.body iter1 r1)
    (iter, r)

/-- [hacspec_sha3_pedantic::step_mappings::rc]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 110:0-138:1
    Visibility: public -/
def step_mappings.rc (t : Std.I64) : RustM Bool := do
  let t1 ← step_mappings.imod t 255#i64
  if t1 = 0#usize
  then ok true
  else
    let r := Array.repeat 9#usize false
    let a ← Array.update r 0#usize true
    let iter ← core.ops.range.RangeInclusive.new 1#usize t1
    let r1 ← step_mappings.rc_loop iter a
    Array.index_usize r1 0#usize

/-- [hacspec_sha3_pedantic::step_mappings::iota]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 149:4-151:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.iota_loop0.body
  {W : Std.Usize} (i_r : Std.I64)
  (iter : core.ops.range.RangeInclusive Std.Usize)
  (round_constant : Array Bool W) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.Usize) × (Array Bool
    W)) (Array Bool W))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done round_constant)
  | core.option.Option.Some j =>
    let i ← lift (UScalar.hcast .I64 j)
    let i1 ← 7#i64 * i_r
    let i2 ← i + i1
    let b ← step_mappings.rc i2
    let i3 ← 1#usize <<< j
    let i4 ← i3 - 1#usize
    let a ← Array.update round_constant i4 b
    ok (cont (iter1, a))

/-- [hacspec_sha3_pedantic::step_mappings::iota]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 149:4-151:5
    Visibility: public -/
@[rust_loop]
def step_mappings.iota_loop0
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.Usize)
  (i_r : Std.I64) (round_constant : Array Bool W) :
  RustM (Array Bool W)
  := do
  loop
    (fun (iter1, round_constant1) => step_mappings.iota_loop0.body i_r iter1
      round_constant1)
    (iter, round_constant)

/-- [hacspec_sha3_pedantic::step_mappings::iota]: loop body 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 158:4-160:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.iota_loop1.body
  {W : Std.Usize} (round_constant : Array Bool W)
  (iter : core.ops.range.Range Std.Usize) (lane : Array Bool W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Bool W))
    (Array Bool W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done lane)
  | core.option.Option.Some z =>
    let b ← Array.index_usize round_constant z
    let b1 ← Array.index_usize lane z
    let a ← Array.update lane z (b1 ^^ b)
    ok (cont (iter1, a))

/-- [hacspec_sha3_pedantic::step_mappings::iota]: loop 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 158:4-160:5
    Visibility: public -/
@[rust_loop]
def step_mappings.iota_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (round_constant : Array Bool W) (lane : Array Bool W) :
  RustM (Array Bool W)
  := do
  loop
    (fun (iter1, lane1) => step_mappings.iota_loop1.body round_constant iter1
      lane1)
    (iter, lane)

/-- [hacspec_sha3_pedantic::step_mappings::iota]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 141:0-163:1
    Visibility: public -/
def step_mappings.iota
  {W : Std.Usize} (a : state_array.StateArray W) (i_r : Std.I64) :
  RustM (state_array.StateArray W)
  := do
  let round_constant := Array.repeat W false
  let i ← state_array.StateArray.L W
  let iter ← core.ops.range.RangeInclusive.new 0#usize i
  let round_constant1 ← step_mappings.iota_loop0 iter i_r round_constant
  let a1 ← Array.index_usize a.a 0#usize
  let lane ← Array.index_usize a1 0#usize
  let lane1 ←
    step_mappings.iota_loop1 { start := 0#usize, «end» := W } round_constant1
      lane
  let (a2, index_mut_back) ← Array.index_mut_usize a.a 0#usize
  let a3 ← Array.update a2 0#usize lane1
  let a4 := index_mut_back a3
  ok { a := a4 }

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop body 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 97:12-99:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 z
    let i ← x + 1#usize
    let i1 ← i % 5#usize
    let a3 ← Array.index_usize a.a i1
    let _ ← Array.index_usize a3 y
    let a4 ← Array.index_usize a3 y
    let b1 ← Array.index_usize a4 z
    let i2 ← x + 2#usize
    let i3 ← i2 % 5#usize
    let a5 ← Array.index_usize a.a i3
    let _ ← Array.index_usize a5 y
    let a6 ← Array.index_usize a5 y
    let b2 ← Array.index_usize a6 z
    let a7 ← Array.index_usize out.a x
    let _ ← Array.index_usize a7 y
    let (a8, index_mut_back) ← Array.index_mut_usize out.a x
    let (a9, index_mut_back1) ← Array.index_mut_usize a8 y
    let a10 ← Array.update a9 z (b ^^ ((¬ b1) && b2))
    let a11 := index_mut_back1 a10
    let a12 := index_mut_back a11
    ok (cont (iter1, { a := a12 }))

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 97:12-99:13
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.chi_loop0_loop0_loop0.body a x y iter1
      out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop body 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 96:8-100:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0_loop0.body
  {W : Std.Usize} (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.chi_loop0_loop0_loop0 { start := 0#usize, «end» := W } a
        out x y
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 96:8-100:9
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.chi_loop0_loop0.body x iter1 a1
      out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 95:4-101:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.chi_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.chi_loop0_loop0 { start := 0#usize, «end» := 5#usize } a
        out x
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::chi]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 95:4-101:5
    Visibility: public -/
@[rust_loop]
def step_mappings.chi_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.chi_loop0.body iter1 a1 out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::chi]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 92:0-103:1
    Visibility: public -/
def step_mappings.chi
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let out ← state_array.StateArray.zero W
  step_mappings.chi_loop0 { start := 0#usize, «end» := 5#usize } a out

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop body 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 83:12-85:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (y : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let i ← 3#usize * y
    let i1 ← x + i
    let i2 ← i1 % 5#usize
    let a1 ← Array.index_usize a.a i2
    let _ ← Array.index_usize a1 x
    let a2 ← Array.index_usize a1 x
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize out.a x
    let _ ← Array.index_usize a3 y
    let (a4, index_mut_back) ← Array.index_mut_usize out.a x
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 y
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 83:12-85:13
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.pi_loop0_loop0_loop0.body a x y iter1
      out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop body 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 82:8-86:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0_loop0.body
  {W : Std.Usize} (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.pi_loop0_loop0_loop0 { start := 0#usize, «end» := W } a
        out x y
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 82:8-86:9
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.pi_loop0_loop0.body x iter1 a1
      out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 81:4-87:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.pi_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.pi_loop0_loop0 { start := 0#usize, «end» := 5#usize } a
        out x
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::pi]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 81:4-87:5
    Visibility: public -/
@[rust_loop]
def step_mappings.pi_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.pi_loop0.body iter1 a1 out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::pi]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 78:0-89:1
    Visibility: public -/
def step_mappings.pi
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let out ← state_array.StateArray.zero W
  step_mappings.pi_loop0 { start := 0#usize, «end» := 5#usize } a out

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 55:4-57:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a 0#usize
    let _ ← Array.index_usize a1 0#usize
    let a2 ← Array.index_usize a1 0#usize
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize out.a 0#usize
    let _ ← Array.index_usize a3 0#usize
    let (a4, index_mut_back) ← Array.index_mut_usize out.a 0#usize
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 0#usize
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 55:4-57:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (out : state_array.StateArray W) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.rho_loop0.body a iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop body 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 66:8-68:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop1_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (w : Std.I64) (x : Std.Usize)
  (y : Std.Usize) (offset : Std.I64) (iter : core.ops.range.Range Std.Usize)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    massert (y < 5#usize)
    let i ← lift (UScalar.hcast .I64 z)
    let i1 ← i - offset
    let i2 ← step_mappings.imod i1 w
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 i2
    let a3 ← Array.index_usize out.a x
    let _ ← Array.index_usize a3 y
    let (a4, index_mut_back) ← Array.index_mut_usize out.a x
    let (a5, index_mut_back1) ← Array.index_mut_usize a4 y
    let a6 ← Array.update a5 z b
    let a7 := index_mut_back1 a6
    let a8 := index_mut_back a7
    ok (cont (iter1, { a := a8 }))

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 66:8-68:9
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop1_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (w : Std.I64) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) (offset : Std.I64) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.rho_loop1_loop0.body a w x y offset
      iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop body 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 63:4-73:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.rho_loop1.body
  {W : Std.Usize} (w : Std.I64) (iter : core.ops.range.Range Std.I64)
  (a : state_array.StateArray W) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.I64) × (state_array.StateArray
    W) × (state_array.StateArray W) × Std.Usize × Std.Usize)
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.I64.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some t =>
    let i ← t + 1#i64
    let i1 ← t + 2#i64
    let i2 ← i * i1
    let offset ← i2 / 2#i64
    let (a1, out1) ←
      step_mappings.rho_loop1_loop0 { start := 0#usize, «end» := W } a w out
        x y offset
    let i3 ← 2#usize * x
    let i4 ← 3#usize * y
    let i5 ← i3 + i4
    let ny ← i5 % 5#usize
    ok (cont (iter1, a1, out1, y, ny))

/-- [hacspec_sha3_pedantic::step_mappings::rho]: loop 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 63:4-73:5
    Visibility: public -/
@[rust_loop]
def step_mappings.rho_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.I64)
  (a : state_array.StateArray W) (w : Std.I64) (out : state_array.StateArray W)
  (x : Std.Usize) (y : Std.Usize) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1, x1, y1) => step_mappings.rho_loop1.body w iter1 a1
      out1 x1 y1)
    (iter, a, out, x, y)

/-- [hacspec_sha3_pedantic::step_mappings::rho]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 50:0-75:1
    Visibility: public -/
def step_mappings.rho
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let w ← lift (UScalar.hcast .I64 W)
  let out ← state_array.StateArray.zero W
  let (a1, out1) ←
    step_mappings.rho_loop0 { start := 0#usize, «end» := W } a out
  step_mappings.rho_loop1 { start := 0#i64, «end» := 24#i64 } a1 w out1
    1#usize 0#usize

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 24:8-26:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (c : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) ((state_array.StateArray W) × (Array (Array Bool W) 5#usize)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, c))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 0#usize
    let a2 ← Array.index_usize a1 0#usize
    let b ← Array.index_usize a2 z
    let _ ← Array.index_usize a1 1#usize
    let a3 ← Array.index_usize a1 1#usize
    let b1 ← Array.index_usize a3 z
    let _ ← Array.index_usize a1 2#usize
    let a4 ← Array.index_usize a1 2#usize
    let b2 ← Array.index_usize a4 z
    let _ ← Array.index_usize a1 3#usize
    let a5 ← Array.index_usize a1 3#usize
    let b3 ← Array.index_usize a5 z
    let _ ← Array.index_usize a1 4#usize
    let a6 ← Array.index_usize a1 4#usize
    let b4 ← Array.index_usize a6 z
    let (a7, index_mut_back) ← Array.index_mut_usize c x
    let a8 ← Array.update a7 z ((((b ^^ b1) ^^ b2) ^^ b3) ^^ b4)
    let a9 := index_mut_back a8
    ok (cont (iter1, a9))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 1:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 24:8-26:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize)
  (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (Array (Array Bool W) 5#usize))
  := do
  loop
    (fun (iter1, c1) => step_mappings.theta_loop0_loop0.body a x iter1 c1)
    (iter, c)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 23:4-27:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop0.body
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (Array (Array Bool W) 5#usize))
    ((state_array.StateArray W) × (Array (Array Bool W) 5#usize)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, c))
  | core.option.Option.Some x =>
    let (a1, c1) ←
      step_mappings.theta_loop0_loop0 { start := 0#usize, «end» := W } a c x
    ok (cont (iter1, a1, c1))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 0:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 23:4-27:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (c : Array (Array Bool W) 5#usize) :
  RustM ((state_array.StateArray W) × (Array (Array Bool W) 5#usize))
  := do
  loop
    (fun (iter1, a1, c1) => step_mappings.theta_loop0.body iter1 a1 c1)
    (iter, a, c)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 3:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 32:8-34:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop1_loop0.body
  {W : Std.Usize} (w : Std.I64) (c : Array (Array Bool W) 5#usize)
  (x : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (d : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) (Array (Array Bool W) 5#usize))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done d)
  | core.option.Option.Some z =>
    let i ← lift (UScalar.hcast .I64 x)
    let i1 ← i - 1#i64
    let i2 ← step_mappings.imod i1 5#i64
    let a ← Array.index_usize c i2
    let b ← Array.index_usize a z
    let i3 ← x + 1#usize
    let i4 ← i3 % 5#usize
    massert (i4 < 5#usize)
    let i5 ← lift (UScalar.hcast .I64 z)
    let i6 ← i5 - 1#i64
    let i7 ← step_mappings.imod i6 w
    let a1 ← Array.index_usize c i4
    let b1 ← Array.index_usize a1 i7
    let (a2, index_mut_back) ← Array.index_mut_usize d x
    let a3 ← Array.update a2 z (b ^^ b1)
    let a4 := index_mut_back a3
    ok (cont (iter1, a4))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 3:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 32:8-34:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop1_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (w : Std.I64)
  (c : Array (Array Bool W) 5#usize) (d : Array (Array Bool W) 5#usize)
  (x : Std.Usize) :
  RustM (Array (Array Bool W) 5#usize)
  := do
  loop
    (fun (iter1, d1) => step_mappings.theta_loop1_loop0.body w c x iter1 d1)
    (iter, d)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 31:4-35:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop1.body
  {W : Std.Usize} (w : Std.I64) (c : Array (Array Bool W) 5#usize)
  (iter : core.ops.range.Range Std.Usize) (d : Array (Array Bool W) 5#usize) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Bool W)
    5#usize)) (Array (Array Bool W) 5#usize))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done d)
  | core.option.Option.Some x =>
    let d1 ←
      step_mappings.theta_loop1_loop0 { start := 0#usize, «end» := W } w c d
        x
    ok (cont (iter1, d1))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 2:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 31:4-35:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop1
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize) (w : Std.I64)
  (c : Array (Array Bool W) 5#usize) (d : Array (Array Bool W) 5#usize) :
  RustM (Array (Array Bool W) 5#usize)
  := do
  loop
    (fun (iter1, d1) => step_mappings.theta_loop1.body w c iter1 d1)
    (iter, d)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 6:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 41:12-43:13
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2_loop0_loop0.body
  {W : Std.Usize} (a : state_array.StateArray W)
  (d : Array (Array Bool W) 5#usize) (x : Std.Usize) (y : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W)) ((state_array.StateArray W) ×
    (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some z =>
    let a1 ← Array.index_usize a.a x
    let _ ← Array.index_usize a1 y
    let a2 ← Array.index_usize a1 y
    let b ← Array.index_usize a2 z
    let a3 ← Array.index_usize d x
    let b1 ← Array.index_usize a3 z
    let a4 ← Array.index_usize out.a x
    let _ ← Array.index_usize a4 y
    let (a5, index_mut_back) ← Array.index_mut_usize out.a x
    let (a6, index_mut_back1) ← Array.index_mut_usize a5 y
    let a7 ← Array.update a6 z (b ^^ b1)
    let a8 := index_mut_back1 a7
    let a9 := index_mut_back a8
    ok (cont (iter1, { a := a9 }))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 6:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 41:12-43:13
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2_loop0_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) (x : Std.Usize) (y : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, out1) => step_mappings.theta_loop2_loop0_loop0.body a d x y
      iter1 out1)
    (iter, out)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 5:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 40:8-44:9
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2_loop0.body
  {W : Std.Usize} (d : Array (Array Bool W) 5#usize) (x : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (a : state_array.StateArray W)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    ((state_array.StateArray W) × (state_array.StateArray W)))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done (a, out))
  | core.option.Option.Some y =>
    let (a1, out1) ←
      step_mappings.theta_loop2_loop0_loop0 { start := 0#usize, «end» := W }
        a d out x y
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 5:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 40:8-44:9
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2_loop0
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) (x : Std.Usize) :
  RustM ((state_array.StateArray W) × (state_array.StateArray W))
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.theta_loop2_loop0.body d x iter1 a1
      out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop body 4:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 39:4-45:5
    Visibility: public -/
@[rust_loop_body]
def step_mappings.theta_loop2.body
  {W : Std.Usize} (d : Array (Array Bool W) 5#usize)
  (iter : core.ops.range.Range Std.Usize) (a : state_array.StateArray W)
  (out : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) ×
    (state_array.StateArray W) × (state_array.StateArray W))
    (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done out)
  | core.option.Option.Some x =>
    let (a1, out1) ←
      step_mappings.theta_loop2_loop0 { start := 0#usize, «end» := 5#usize }
        a d out x
    ok (cont (iter1, a1, out1))

/-- [hacspec_sha3_pedantic::step_mappings::theta]: loop 4:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 39:4-45:5
    Visibility: public -/
@[rust_loop]
def step_mappings.theta_loop2
  {W : Std.Usize} (iter : core.ops.range.Range Std.Usize)
  (a : state_array.StateArray W) (d : Array (Array Bool W) 5#usize)
  (out : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1, out1) => step_mappings.theta_loop2.body d iter1 a1 out1)
    (iter, a, out)

/-- [hacspec_sha3_pedantic::step_mappings::theta]:
    Source: 'sha3-pedantic/src/step_mappings.rs', lines 18:0-47:1
    Visibility: public -/
def step_mappings.theta
  {W : Std.Usize} (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  let w ← lift (UScalar.hcast .I64 W)
  let a1 := Array.repeat W false
  let c := Array.repeat 5#usize a1
  let (a2, c1) ←
    step_mappings.theta_loop0 { start := 0#usize, «end» := 5#usize } a c
  let a3 := Array.repeat W false
  let d := Array.repeat 5#usize a3
  let d1 ←
    step_mappings.theta_loop1 { start := 0#usize, «end» := 5#usize } w c1 d
  step_mappings.theta_loop2 { start := 0#usize, «end» := 5#usize } a2 d1 a2

/-- [hacspec_sha3_pedantic::keccak_p::rnd]:
    Source: 'sha3-pedantic/src/keccak_p.rs', lines 8:0-10:1
    Visibility: public -/
def keccak_p.rnd
  {W : Std.Usize} (a : state_array.StateArray W) (i_r : Std.I64) :
  RustM (state_array.StateArray W)
  := do
  let sa ← step_mappings.theta a
  let sa1 ← step_mappings.rho sa
  let sa2 ← step_mappings.pi sa1
  let sa3 ← step_mappings.chi sa2
  step_mappings.iota sa3 i_r

/-- [hacspec_sha3_pedantic::keccak_p::keccak_p]: loop body 0:
    Source: 'sha3-pedantic/src/keccak_p.rs', lines 22:4-24:5
    Visibility: public -/
@[rust_loop_body]
def keccak_p.keccak_p_loop.body
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.I64)
  (a : state_array.StateArray W) :
  RustM (ControlFlow ((core.ops.range.RangeInclusive Std.I64) ×
    (state_array.StateArray W)) (state_array.StateArray W))
  := do
  let (o, iter1) ←
    core.ops.range.RangeInclusive.Insts.CoreIterTraitsIteratorIterator.next
      core.I64.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done a)
  | core.option.Option.Some i_r =>
    let a1 ← keccak_p.rnd a i_r
    ok (cont (iter1, a1))

/-- [hacspec_sha3_pedantic::keccak_p::keccak_p]: loop 0:
    Source: 'sha3-pedantic/src/keccak_p.rs', lines 22:4-24:5
    Visibility: public -/
@[rust_loop]
def keccak_p.keccak_p_loop
  {W : Std.Usize} (iter : core.ops.range.RangeInclusive Std.I64)
  (a : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  loop
    (fun (iter1, a1) => keccak_p.keccak_p_loop.body iter1 a1)
    (iter, a)

/-- [hacspec_sha3_pedantic::keccak_p::keccak_p]:
    Source: 'sha3-pedantic/src/keccak_p.rs', lines 15:0-29:1
    Visibility: public -/
def keccak_p.keccak_p
  (W : Std.Usize) (s : Slice Bool) (n_r : Std.Usize) :
  RustM (alloc.vec.Vec Bool)
  := do
  let a ← state_array.StateArray.from_bits W s
  let i ← state_array.StateArray.L W
  let i1 ← lift (UScalar.hcast .I64 i)
  let i2 ← 2#i64 * i1
  let i3 ← 12#i64 + i2
  let last ← i3 - 1#i64
  let i4 ← lift (UScalar.hcast .I64 n_r)
  let i5 ← last - i4
  let first ← i5 + 1#i64
  let iter ← core.ops.range.RangeInclusive.new first last
  let a1 ← keccak_p.keccak_p_loop iter a
  state_array.StateArray.to_bits a1

/-- [hacspec_sha3_pedantic::sponge::{impl hacspec_sha3_pedantic::sponge::Components for hacspec_sha3_pedantic::sponge::Keccak1600}::f]:
    Source: 'sha3-pedantic/src/sponge.rs', lines 81:4-83:5
    Visibility: public -/
def sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents.f
  (self : sponge.Keccak1600) (s : Slice Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  keccak_p.keccak_p 64#usize s 24#usize

/-- Trait implementation: [hacspec_sha3_pedantic::sponge::{impl hacspec_sha3_pedantic::sponge::Components for hacspec_sha3_pedantic::sponge::Keccak1600}]
    Source: 'sha3-pedantic/src/sponge.rs', lines 80:0-88:1 -/
@[reducible]
def sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents :
  sponge.Components sponge.Keccak1600 := {
  f := sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents.f
  pad := sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents.pad
}

/-- [hacspec_sha3_pedantic::sponge::B]
    Source: 'sha3-pedantic/src/sponge.rs', lines 74:0-74:26
    Visibility: public -/
@[global_simps, irreducible] def sponge.B : Std.Usize := 1600#usize

/-- [hacspec_sha3_pedantic::sponge::sponge]: loop body 0:
    Source: 'sha3-pedantic/src/sponge.rs', lines 54:4-57:5
    Visibility: public -/
@[rust_loop_body]
def sponge.sponge_loop0.body
  {C : Type} (ComponentsInst : sponge.Components C) (components : C)
  (r : Std.Usize) (p : alloc.vec.Vec Bool) (c : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (s : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let (o, iter1) ←
    core.ops.range.Range.Insts.CoreIterTraitsIteratorIterator.next
      core.Usize.Insts.CoreIterRangeStep iter
  match o with
  | core.option.Option.None => ok (done s)
  | core.option.Option.Some i =>
    let i1 ← i * r
    let i2 ← i + 1#usize
    let i3 ← i2 * r
    let s1 ←
      alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Bool) p { start := i1, «end» := i3 }
    let v ← bits.zeros c
    let s2 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
    let block ← bits.concat s1 s2
    let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref s
    let s4 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref block
    let v1 ← bits.xor s3 s4
    let s5 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
    let s6 ← ComponentsInst.f components s5
    ok (cont (iter1, s6))

/-- [hacspec_sha3_pedantic::sponge::sponge]: loop 0:
    Source: 'sha3-pedantic/src/sponge.rs', lines 54:4-57:5
    Visibility: public -/
@[rust_loop]
def sponge.sponge_loop0
  {C : Type} (ComponentsInst : sponge.Components C)
  (iter : core.ops.range.Range Std.Usize) (components : C) (r : Std.Usize)
  (p : alloc.vec.Vec Bool) (c : Std.Usize) (s : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (iter1, s1) => sponge.sponge_loop0.body ComponentsInst components r p
      c iter1 s1)
    (iter, s)

/-- [hacspec_sha3_pedantic::sponge::sponge]: loop body 1:
    Source: 'sha3-pedantic/src/sponge.rs', lines 60:4-70:5
    Visibility: public -/
@[rust_loop_body]
def sponge.sponge_loop1.body
  {C : Type} (ComponentsInst : sponge.Components C) (components : C)
  (r : Std.Usize) (d : Std.Usize) (s : alloc.vec.Vec Bool)
  (z : alloc.vec.Vec Bool) :
  RustM (ControlFlow ((alloc.vec.Vec Bool) × (alloc.vec.Vec Bool))
    (alloc.vec.Vec Bool))
  := do
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref s
  let head ← bits.trunc s1 r
  let s2 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref z
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref head
  let z1 ← bits.concat s2 s3
  let i ← alloc.vec.Vec.len z1
  if d <= i
  then ok (done z1)
  else let s4 ← ComponentsInst.f components s1
       ok (cont (s4, z1))

/-- [hacspec_sha3_pedantic::sponge::sponge]: loop 1:
    Source: 'sha3-pedantic/src/sponge.rs', lines 60:4-70:5
    Visibility: public -/
@[rust_loop]
def sponge.sponge_loop1
  {C : Type} (ComponentsInst : sponge.Components C) (components : C)
  (r : Std.Usize) (d : Std.Usize) (s : alloc.vec.Vec Bool)
  (z : alloc.vec.Vec Bool) :
  RustM (alloc.vec.Vec Bool)
  := do
  loop
    (fun (s1, z1) => sponge.sponge_loop1.body ComponentsInst components r d s1
      z1)
    (s, z)

/-- [hacspec_sha3_pedantic::sponge::sponge]:
    Source: 'sha3-pedantic/src/sponge.rs', lines 43:0-71:1
    Visibility: public -/
def sponge.sponge
  {C : Type} (ComponentsInst : sponge.Components C) (components : C)
  (b : Std.Usize) (r : Std.Usize) (n : Slice Bool) (d : Std.Usize) :
  RustM (alloc.vec.Vec Bool)
  := do
  let i ← core.slice.Slice.len n
  let v ← ComponentsInst.pad components r i
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let p ← bits.concat n s
  let i1 ← alloc.vec.Vec.len p
  let blocks ← i1 / r
  let c ← b - r
  let s1 ← bits.zeros b
  let s2 ←
    sponge.sponge_loop0 ComponentsInst { start := 0#usize, «end» := blocks }
      components r p c s1
  let z ← alloc.vec.Vec.new Bool
  let z1 ← sponge.sponge_loop1 ComponentsInst components r d s2 z
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref z1
  bits.trunc s3 d

/-- [hacspec_sha3_pedantic::sponge::keccak_c]:
    Source: 'sha3-pedantic/src/sponge.rs', lines 91:0-93:1
    Visibility: public -/
def sponge.keccak_c
  (c : Std.Usize) (n : Slice Bool) (d : Std.Usize) :
  RustM (alloc.vec.Vec Bool)
  := do
  let i ← sponge.B - c
  sponge.sponge sponge.Keccak1600.Insts.Hacspec_sha3_pedanticSpongeComponents
    () sponge.B i n d

/-- [hacspec_sha3_pedantic::sha3::HASH_SUFFIX]
    Source: 'sha3-pedantic/src/sha3.rs', lines 10:0-10:48
    Visibility: public -/
@[global_simps, irreducible]
def sha3.HASH_SUFFIX : Array Bool 2#usize := Array.make 2#usize [ false, true ]

/-- [hacspec_sha3_pedantic::sha3::sha3_224]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 16:0-18:1
    Visibility: public -/
def sha3.sha3_224 (m : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 448#usize s1 224#usize

/-- [hacspec_sha3_pedantic::bytes::sha3_224]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 14:8-19:9
    Visibility: public -/
def bytes.sha3_224 (m : Slice Std.U8) : RustM (Array Std.U8 28#usize) := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let v1 ← sha3.sha3_224 s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  let digest ← bits.b2h s1
  let out := Array.repeat 28#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s4 ←
    core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s2 s3
  ok (to_slice_mut_back s4)

/-- [hacspec_sha3_pedantic::sha3::sha3_256]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 21:0-23:1
    Visibility: public -/
def sha3.sha3_256 (m : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 512#usize s1 256#usize

/-- [hacspec_sha3_pedantic::bytes::sha3_256]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 14:8-19:9
    Visibility: public -/
def bytes.sha3_256 (m : Slice Std.U8) : RustM (Array Std.U8 32#usize) := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let v1 ← sha3.sha3_256 s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  let digest ← bits.b2h s1
  let out := Array.repeat 32#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s4 ←
    core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s2 s3
  ok (to_slice_mut_back s4)

/-- [hacspec_sha3_pedantic::sha3::sha3_384]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 26:0-28:1
    Visibility: public -/
def sha3.sha3_384 (m : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 768#usize s1 384#usize

/-- [hacspec_sha3_pedantic::bytes::sha3_384]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 14:8-19:9
    Visibility: public -/
def bytes.sha3_384 (m : Slice Std.U8) : RustM (Array Std.U8 48#usize) := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let v1 ← sha3.sha3_384 s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  let digest ← bits.b2h s1
  let out := Array.repeat 48#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s4 ←
    core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s2 s3
  ok (to_slice_mut_back s4)

/-- [hacspec_sha3_pedantic::sha3::sha3_512]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 31:0-33:1
    Visibility: public -/
def sha3.sha3_512 (m : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.HASH_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 1024#usize s1 512#usize

/-- [hacspec_sha3_pedantic::bytes::sha3_512]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 14:8-19:9
    Visibility: public -/
def bytes.sha3_512 (m : Slice Std.U8) : RustM (Array Std.U8 64#usize) := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let v1 ← sha3.sha3_512 s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  let digest ← bits.b2h s1
  let out := Array.repeat 64#usize 0#u8
  let (s2, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s3 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref digest
  let s4 ←
    core.slice.Slice.copy_from_slice core.U8.Insts.CoreMarkerCopy s2 s3
  ok (to_slice_mut_back s4)

/-- [hacspec_sha3_pedantic::sha3::XOF_SUFFIX]
    Source: 'sha3-pedantic/src/sha3.rs', lines 13:0-13:58
    Visibility: public -/
@[global_simps, irreducible]
def sha3.XOF_SUFFIX : Array Bool 4#usize := Array.repeat 4#usize true

/-- [hacspec_sha3_pedantic::sha3::shake128]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 36:0-38:1
    Visibility: public -/
def sha3.shake128
  (m : Slice Bool) (d : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.XOF_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 256#usize s1 d

/-- [hacspec_sha3_pedantic::bytes::shake128]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 37:0-39:1
    Visibility: public -/
def bytes.shake128
  (m : Slice Std.U8) (out_bytes : Std.Usize) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let i ← 8#usize * out_bytes
  let v1 ← sha3.shake128 s i
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  bits.b2h s1

/-- [hacspec_sha3_pedantic::sha3::shake256]:
    Source: 'sha3-pedantic/src/sha3.rs', lines 41:0-43:1
    Visibility: public -/
def sha3.shake256
  (m : Slice Bool) (d : Std.Usize) : RustM (alloc.vec.Vec Bool) := do
  let s ← lift (Array.to_slice sha3.XOF_SUFFIX)
  let v ← bits.concat m s
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  sponge.keccak_c 512#usize s1 d

/-- [hacspec_sha3_pedantic::bytes::shake256]:
    Source: 'sha3-pedantic/src/bytes.rs', lines 42:0-44:1
    Visibility: public -/
def bytes.shake256
  (m : Slice Std.U8) (out_bytes : Std.Usize) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let v ← bits.h2b_full m
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v
  let i ← 8#usize * out_bytes
  let v1 ← sha3.shake256 s i
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref v1
  bits.b2h s1

/-- [hacspec_sha3_pedantic::keccak_p::keccak_f]:
    Source: 'sha3-pedantic/src/keccak_p.rs', lines 32:0-34:1
    Visibility: public -/
def keccak_p.keccak_f
  (W : Std.Usize) (s : Slice Bool) : RustM (alloc.vec.Vec Bool) := do
  let i ← state_array.StateArray.L W
  let i1 ← 2#usize * i
  let i2 ← 12#usize + i1
  keccak_p.keccak_p W s i2

/-- [hacspec_sha3_pedantic::state_array::{impl core::clone::Clone for hacspec_sha3_pedantic::state_array::StateArray<W>}::clone]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:9-16:14
    Visibility: public -/
def state_array.StateArray.Insts.CoreCloneClone.clone
  {W : Std.Usize} (self : state_array.StateArray W) :
  RustM (state_array.StateArray W)
  := do
  ok self

/-- Trait implementation: [hacspec_sha3_pedantic::state_array::{impl core::clone::Clone for hacspec_sha3_pedantic::state_array::StateArray<W>}]
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:9-16:14 -/
@[reducible]
impl_def state_array.StateArray.Insts.CoreCloneClone (W : Std.Usize) :
  core.clone.Clone (state_array.StateArray W) := {
  clone := state_array.StateArray.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    (state_array.StateArray.Insts.CoreCloneClone W)
}

/-- Trait implementation: [hacspec_sha3_pedantic::state_array::{impl core::marker::Copy for hacspec_sha3_pedantic::state_array::StateArray<W>}]
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:16-16:20 -/
@[reducible]
def state_array.StateArray.Insts.CoreMarkerCopy (W : Std.Usize) :
  core.marker.Copy (state_array.StateArray W) := {
  cloneCloneInst := state_array.StateArray.Insts.CoreCloneClone W
}

/-- Trait implementation: [hacspec_sha3_pedantic::state_array::{impl core::marker::StructuralPartialEq for hacspec_sha3_pedantic::state_array::StateArray<W>}]
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:22-16:31 -/
@[reducible]
def state_array.StateArray.Insts.CoreMarkerStructuralPartialEq (W : Std.Usize)
  : core.marker.StructuralPartialEq (state_array.StateArray W) := {
}

/-- [hacspec_sha3_pedantic::state_array::{impl core::cmp::PartialEq<hacspec_sha3_pedantic::state_array::StateArray<W>> for hacspec_sha3_pedantic::state_array::StateArray<W>}::eq]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:22-16:31
    Visibility: public -/
def state_array.StateArray.Insts.CoreCmpPartialEqStateArray.eq
  {W : Std.Usize} (self : state_array.StateArray W)
  (other : state_array.StateArray W) :
  RustM Bool
  := do
  core.Array.Insts.CoreCmpPartialEqArray.eq
    (core.Array.Insts.CoreCmpPartialEqArray 5#usize
    (core.Array.Insts.CoreCmpPartialEqArray W
    core.Bool.Insts.CoreCmpPartialEqBool)) self.a other.a

/-- Trait implementation: [hacspec_sha3_pedantic::state_array::{impl core::cmp::PartialEq<hacspec_sha3_pedantic::state_array::StateArray<W>> for hacspec_sha3_pedantic::state_array::StateArray<W>}]
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:22-16:31 -/
@[reducible]
impl_def state_array.StateArray.Insts.CoreCmpPartialEqStateArray (W :
  Std.Usize) : core.cmp.PartialEq (state_array.StateArray W)
  (state_array.StateArray W) := {
  eq := state_array.StateArray.Insts.CoreCmpPartialEqStateArray.eq
  ne := core.cmp.PartialEq.ne.default
    (state_array.StateArray.Insts.CoreCmpPartialEqStateArray W)
}

/-- Trait implementation: [hacspec_sha3_pedantic::state_array::{impl core::cmp::Eq for hacspec_sha3_pedantic::state_array::StateArray<W>}]
    Source: 'sha3-pedantic/src/state_array.rs', lines 16:33-16:35 -/
@[reducible]
def state_array.StateArray.Insts.CoreCmpEq (W : Std.Usize) : core.cmp.Eq
  (state_array.StateArray W) := {
  PartialEqInst := state_array.StateArray.Insts.CoreCmpPartialEqStateArray W
}

/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::W#1]
    Source: 'sha3-pedantic/src/state_array.rs', lines 24:4-24:27
    Visibility: public -/
@[global_simps, irreducible]
def state_array.StateArray.W_1 (W : Std.Usize) : Std.Usize := W

end hacspec_sha3_pedantic
