-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_sha3_pedantic]: proof obligations
import Aeneas
import CoreModels
import HacspecSha3Pedantic.Extraction.Types
import HacspecSha3Pedantic.Extraction.Funs
import HacspecSha3Pedantic.Extraction.Specs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_sha3_pedantic

@[spec]
theorem bits.trunc.spec.proof (x : Slice Bool) (s : Std.Usize) :
  bits.trunc.spec x s
  := by sorry

@[spec]
theorem bits.xor.spec.proof (x : Slice Bool) (y : Slice Bool) :
  bits.xor.spec x y
  := by sorry

@[spec]
theorem bits.h2b.spec.proof (h : Slice Std.U8) (n : Std.Usize) :
  bits.h2b.spec h n
  := by sorry

@[spec]
theorem state_array.StateArray.from_bits.spec.proof (W : Std.Usize)
  (s : Slice Bool) : state_array.StateArray.from_bits.spec W s
  := by sorry

end hacspec_sha3_pedantic
