-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_sha3_pedantic]: specs (statements of correctness)
import Aeneas
import CoreModels
import Hax
import HacspecSha3Pedantic.Extraction.Types
import HacspecSha3Pedantic.Extraction.Funs
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace hacspec_sha3_pedantic


/-- [hacspec_sha3_pedantic::bits::trunc::pre]:
    Source: 'sha3-pedantic/src/bits.rs', lines 20:16-20:47 -/
@[reducible]
def bits.trunc.pre (x : Slice Bool) (s : Std.Usize) : RustM Bool := do
  let i ← core.slice.Slice.len x
  ok (s <= i)

def bits.trunc.spec (x : Slice Bool) (s : Std.Usize) : Prop :=
  (bits.trunc.pre x s).holds →
  ⦃ ⌜ True ⌝ ⦄
  bits.trunc x s
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hacspec_sha3_pedantic::bits::xor::pre]:
    Source: 'sha3-pedantic/src/bits.rs', lines 52:16-52:53 -/
@[reducible]
def bits.xor.pre (x : Slice Bool) (y : Slice Bool) : RustM Bool := do
  let i ← core.slice.Slice.len x
  let i1 ← core.slice.Slice.len y
  ok (i = i1)

def bits.xor.spec (x : Slice Bool) (y : Slice Bool) : Prop :=
  (bits.xor.pre x y).holds →
  ⦃ ⌜ True ⌝ ⦄
  bits.xor x y
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hacspec_sha3_pedantic::bits::h2b::pre]:
    Source: 'sha3-pedantic/src/bits.rs', lines 69:16-69:51 -/
@[reducible]
def bits.h2b.pre (h : Slice Std.U8) (n : Std.Usize) : RustM Bool := do
  let i ← core.slice.Slice.len h
  let i1 ← 8#usize * i
  ok (n <= i1)

def bits.h2b.spec (h : Slice Std.U8) (n : Std.Usize) : Prop :=
  (bits.h2b.pre h n).holds →
  ⦃ ⌜ True ⌝ ⦄
  bits.h2b h n
  ⦃ ⇓ res => ⌜ True ⌝ ⦄


/-- [hacspec_sha3_pedantic::state_array::{hacspec_sha3_pedantic::state_array::StateArray<W>}::from_bits::pre]:
    Source: 'sha3-pedantic/src/state_array.rs', lines 22:16-22:35 -/
@[reducible]
def state_array.StateArray.from_bits.pre
  (W : Std.Usize) (s : Slice Bool) : RustM Bool := do
  let i ← core.slice.Slice.len s
  let i1 ← 25#usize * W
  ok (i = i1)

def state_array.StateArray.from_bits.spec (W : Std.Usize) (s : Slice Bool)
  : Prop :=
  (state_array.StateArray.from_bits.pre W s).holds →
  ⦃ ⌜ True ⌝ ⦄
  state_array.StateArray.from_bits W s
  ⦃ ⇓ res => ⌜ True ⌝ ⦄

end hacspec_sha3_pedantic
