-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [hacspec_sha3_pedantic]: type definitions
import Aeneas
import CoreModels
import HacspecSha3Pedantic.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace hacspec_sha3_pedantic

/-- [hacspec_sha3_pedantic::sponge::Keccak1600]
    Source: 'sha3-pedantic/src/sponge.rs', lines 113:0-113:22
    Visibility: public -/
@[reducible]
def sponge.Keccak1600 := Unit

/-- [hacspec_sha3_pedantic::state_array::StateArray]
    Source: 'sha3-pedantic/src/state_array.rs', lines 17:0-20:1
    Visibility: public -/
structure state_array.StateArray (W : Std.Usize) where
  a : Array (Array (Array Bool W) 5#usize) 5#usize

/-- Trait declaration: [hacspec_sha3_pedantic::sponge::Components]
    Source: 'sha3-pedantic/src/sponge.rs', lines 32:0-42:1
    Visibility: public -/
structure sponge.Components (Self : Type) where
  B : RustM Std.Usize
  f : Self → Slice Bool → RustM (alloc.vec.Vec Bool)
  pad : Self → Std.Usize → Std.Usize → RustM (alloc.vec.Vec Bool)

/-- [hacspec_sha3_pedantic::sponge::Sponge]
    Source: 'sha3-pedantic/src/sponge.rs', lines 54:0-59:1
    Visibility: public -/
structure sponge.Sponge (C : Type) where
  components : C
  r : Std.Usize

end hacspec_sha3_pedantic
