name: Platform - Build & Test

on:
  merge_group:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  platform:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: linux
    defaults:
      run:
        shell: bash
        working-directory: crates/sys/platform

    steps:
      - uses: actions/checkout@v6

      - name: Update dependencies
        run: cargo update

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 🏃🏻‍♀️ Test
        run: cargo test --verbose -- --nocapture

      - name: 🏃🏻‍♀️ Test Release
        run: cargo test --verbose --release -- --nocapture

  platform-build-test-status:
    if: ${{ always() }}
    needs: [platform]
    runs-on: linux
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
