name: secrets - Build & Test

on:
  merge_group:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: linux
    defaults:
      run:
        shell: bash
        working-directory: crates/utils/secrets

    steps:
      - uses: actions/checkout@v6

      # Build ...

      - name: 🔨 Build
        run: |
          rustc --print=cfg
          cargo build --verbose

      - name: 🔨 Build Release
        run: cargo build --verbose --release

      # Test ...

      - name: 🏃🏻‍♀️ Test
        run: |
          cargo clean
          cargo test --verbose

      - name: 🏃🏻‍♀️ Test Release
        run: |
          cargo clean
          cargo test --verbose --release

      - name: 🏃🏻‍♀️ Test Secret Independence
        run: |
          cargo clean
          cargo test --verbose --features check-secret-independence

      - name: 🏃🏻‍♀️ Test Release Secret Independence
        run: |
          cargo clean
          cargo test --verbose --release --features check-secret-independence
          
      - name: 🏃🏻‍♀️ Test Portable
        run: |
          cargo clean
          LIBCRUX_DISABLE_SIMD128=1 LIBCRUX_DISABLE_SIMD256=1 cargo test --verbose

      - name: 🏃🏻‍♀️ Test Portable Release
        run: |
          cargo clean
          LIBCRUX_DISABLE_SIMD128=1 LIBCRUX_DISABLE_SIMD256=1 cargo test --verbose --release
          
  secrets-build-test-status:
    if: ${{ always() }}
    needs: [build]
    runs-on: linux
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
