name: Sync libcrux into libcrux-evit

on:
  schedule:
    - cron: "0 0 * * 1" 
  workflow_dispatch:

jobs:
  sync:
    permissions:
      pull-requests: write
      contents: write
      # actions:	read/write	none	read
      # attestations:	read/write	none	read
      # checks:	read/write	none	read
      # contents:	read/write	read	read
      # deployments:	read/write	none	read
      # discussions:	read/write	none	read
      # id-token:	none	none	none
      # issues:	read/write	none	read
      # metadata:	read	read	read
      # packages:	read/write	read	read
      # pages:	read/write	none	read
      # pull-requests:	read/write	none	read
      # repository-projects:	read/write	none	read
      # security-events:	read/write	none	read
      # statuses:	read/write	none	read
    runs-on: linux
    if: github.repository == 'cryspen/libcrux-evit'
    steps:
      - name: Checkout libcrux-evit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add libcrux as upstream
        run: |
          git remote add upstream https://github.com/cryspen/libcrux.git || true
          git fetch upstream

      - name: Add libcrux-evit as origin
        run: |
          git remote add origin https://github.com/cryspen/libcrux-evit.git || true
          git fetch origin
          
      - name: Create and update sync branch
        run: |
          git checkout -B merge-public-libcrux upstream/main
          git restore --source origin/main --staged --worktree -- .github
          git commit -m "Restore libcrux-evit CI workflows"
          git push --set-upstream origin merge-public-libcrux --force

      - name: Create pull request
        run: gh pr create -B main -H merge-public-libcrux --title 'Synchronize with upstream libcrux' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: cryspen/libcrux-evit
