name: Traits - Build

on:
  merge_group:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: linux
    defaults:
      run:
        shell: bash
        working-directory: traits

    steps:
      - uses: actions/checkout@v6

      # Build ...

      - name: 🔨 Build
        run: |
          rustc --print=cfg
          cargo build --verbose
          cargo build --verbose -F error-in-core

      - name: 🔨 Build Release
        run: |
          cargo build --verbose --release
          cargo build --verbose --release -F error-in-core


  traits-build-status:
    if: ${{ always() }}
    needs: [build]
    runs-on: linux
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }} 
        run: exit 0 
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }} 
        run: exit 1 
